# Generated by Django 5.1.7 on 2025-03-11 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('results_json', models.JSONField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_change_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ps_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ev_ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fcf_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('quality_score', models.IntegerField(blank=True, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('operating_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cash', models.BigIntegerField(blank=True, null=True)),
                ('total_debt', models.BigIntegerField(blank=True, null=True)),
                ('net_cash', models.BigIntegerField(blank=True, null=True)),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('payout_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ex_dividend_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='stock_data.company')),
            ],
        ),
    ]
